name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 8.x 
    - run: npm install 
    - run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt-get update
    - run: sudo apt-get -y install openssh-client
    - run: scp me.json ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.REMOTE_MEJSON }}